<?php
//zend by QQ:2172298892  瑾梦网络  禁止倒卖 一经发现停止任何服务
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>";
echo $lang['checking_title'];
echo "</title>\r\n<link href=\"styles/install.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<script type=\"text/javascript\" src=\"js/transport_jquery.js\"></script>\r\n<script type=\"text/javascript\" src=\"js/common.js\"></script>\r\n</head>\r\n<body id=\"checking\">\r\n";
include ROOT_PATH . 'install/templates/header.php';
echo "    <div class=\"wrapper\">\r\n    \t<div class=\"w1000\">\r\n        \t<div class=\"attention\" id=\"attention\">\r\n            \t\r\n            </div>\r\n            <div class=\"content\">\r\n            \t<div class=\"tab\">\r\n                \t<div class=\"step\">\r\n                    \t<div class=\"warp\">\r\n                        \t<i>1</i>\r\n                        \t<span>欢迎使用</span>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"step curr\">\r\n                    \t<div class=\"warp\">\r\n                        \t<i>2</i>\r\n                        \t<span>检查环境</span>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"step\">\r\n                    \t<div class=\"warp\">\r\n                        \t<i>3</i>\r\n                        \t<span>配置系统</span>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n                <div class=\"zoome\" id=\"zoome\">\r\n                \r\n                </div>\r\n                <div class=\"right\" id=\"right_ad\">\r\n                \t\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"footer\">\r\n     \t\t";
include ROOT_PATH . 'install/templates/copyright.php';
echo "</div>\r\n\t\t</div>\r\n    </div>\r\n<script type=\"text/javascript\">\r\nAjax.call('cloud.php?step=check','', check_api, 'GET', 'TEXT','FLASE');\r\nAjax.call('cloud.php?step=right_ad','', right_ad_api, 'GET', 'TEXT','FLASE');\r\nAjax.call('cloud.php?step=update_mend','', update_mend_api, 'GET', 'TEXT','FLASE');\r\nfunction check_api(result)\r\n{\r\n  if(result)\r\n  {\r\n    setInnerHTML('zoome',result);\r\n    setInputCheckedStatus();\r\n\r\n    \$(\"js-pre-step\").onclick = function() {\r\n        location.href=\"./index.php?lang=\" + getAddressLang() + \"&step=welcome\";\r\n    };\r\n    \$(\"js-recheck\").onclick = function () {\r\n        location.href=\"./index.php?lang=\" + getAddressLang() + \"&step=check\";\r\n    };\r\n    \$(\"js-submit\").onclick = function () {\r\n        this.form.action=\"index.php?lang=\" + getAddressLang() + \"&step=setting_ui\" + \"&ui=\" + \$('userinterface').value;\r\n    };\r\n  }\r\n}\r\n\r\nfunction right_ad_api(result)\r\n{\r\n  if(result)\r\n  {\r\n    setInnerHTML('right_ad',result);\r\n  }\r\n}\r\nfunction update_mend_api(result)\r\n{\r\n  if(result)\r\n  {\r\n    setInnerHTML('attention',result);\r\n  }\r\n}\r\n</script>\r\n</body>\r\n</html>";

?>
