<?php
//zend by QQ:2172298892  瑾梦网络  禁止倒卖 一经发现停止任何服务
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>";
echo $lang['welcome_title'];
echo "</title>\r\n<link href=\"styles/install.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n\r\n<script type=\"text/javascript\" src=\"js/transport_jquery.js\"></script>\r\n<script type=\"text/javascript\" src=\"js/common.js\"></script>\r\n\r\n<script type=\"text/javascript\" src=\"js/jquery-1.9.1.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"js/scroll.js\"></script>\r\n\r\n</head>\r\n<body id=\"welcome\">\r\n";
include ROOT_PATH . 'install/templates/header.php';
echo "    <div class=\"wrapper\">\r\n    \t<div class=\"w1000\">\r\n        \t<div class=\"attention\" id=\"attention\">\r\n            \t\r\n            </div>\r\n            <div class=\"content\">\r\n            \t<div class=\"tab\">\r\n                \t<div class=\"step curr\">\r\n                    \t<div class=\"warp\">\r\n                        \t<i>1</i>\r\n                        \t<span>欢迎使用</span>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"step\">\r\n                    \t<div class=\"warp\">\r\n                        \t<i>2</i>\r\n                        \t<span>检查环境</span>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"step\">\r\n                    \t<div class=\"warp\">\r\n                        \t<i>3</i>\r\n                        \t<span>配置系统</span>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n                <div class=\"zoome\" id=\"zoome\">\r\n                  <form method=\"post\">\r\n                    <div class=\"scrollBody\" id=\"scrollBody\">\r\n                        <div class=\"desc\" id=\"scrollMap\">\r\n                            <ul id=\"content\">\r\n                                \r\n                            </ul>\r\n                        </div>\r\n                        <div class=\"scrollBar\" id=\"scrollBar\">\r\n                            <p id=\"city_bar\"></p>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"tfoot\">\r\n                        <div class=\"tfoot_left\">\r\n                            <input type=\"checkbox\" id=\"js-agree\" />\r\n                            <label for=\"js-agree\">";
echo $lang['agree_license'];
echo "</label>\r\n                        </div>\r\n                        <div class=\"tfoot_right\">\r\n                        <input type=\"submit\" id=\"js-submit\" disabled=\"disabled\" class=\"btn\" value=\"";
echo $lang['next_step'];
echo $lang['setup_environment'];
echo "\" />\r\n                    \t\r\n                        </div>\r\n                        <input name=\"ucapi\" type=\"hidden\" value=\"";
echo $ucapi;
echo "\" />\r\n                        <input name=\"ucfounderpw\" type=\"hidden\" value=\"";
echo $ucfounderpw;
echo "\" />\r\n                    </div>\r\n                    </form>\r\n                </div>\r\n                <div class=\"right\" id=\"right_ad\">\r\n                \t\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"footer\">\r\n     \t\t";
include ROOT_PATH . 'install/templates/copyright.php';
echo "        </div>\r\n    </div>\r\n<script type=\"text/javascript\">\r\n\$(\"#zoome\").jScroll({id:\"scrollBody\"});\r\n\r\nAjax.call('cloud.php?step=welcome','', welcome_api, 'GET', 'TEXT','FLASE');\r\nAjax.call('cloud.php?step=right_ad','', right_ad_api, 'GET', 'TEXT','FLASE');\r\nAjax.call('cloud.php?step=update_mend','', update_mend_api, 'GET', 'TEXT','FLASE');\r\nfunction welcome_api(result)\r\n{\r\n  if(result)\r\n  {\r\n    setInnerHTML('content',result);\r\n    setInputCheckedStatus();\r\n\r\n    var agree = \$(\"#js-agree\");\r\n    var Submit = \$(\"#js-submit\");\r\n\t\r\n\tagree.click(function(){\r\n\t\tif(agree.prop(\"checked\")==true){\r\n\t\t\tSubmit.removeAttr('disabled');\r\n\t\t\tSubmit.addClass(\"btn-curr\");\r\n\t\t\tSubmit.click(function(){\r\n\t\t\t\t\$(\"form\").submit(function(){\r\n\t\t\t\t\t\$(this).attr(\"action\",\"./index.php?lang=\" + getAddressLang() +\"&step=check\");\r\n\t\t\t\t});\r\n\t\t\t});\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tSubmit.attr('disabled','true');\r\n\t\t\tSubmit.removeClass(\"btn-curr\");\r\n\t\t}\r\n\t});\t\r\n\t\r\n  }\r\n}\r\n\r\nfunction right_ad_api(result)\r\n{\r\n  if(result)\r\n  {\r\n    setInnerHTML('right_ad',result);\r\n  }\r\n}\r\nfunction update_mend_api(result)\r\n{\r\n  if(result)\r\n  {\r\n    setInnerHTML('attention',result);\r\n  }\r\n}\r\n\r\n</script>\r\n</body>\r\n</html>";

?>
